openapi: 3.0.3
info:
  title: Calendar API
  version: v4.1
servers:
  - url: /
paths:
  /hello:
    get:
      description: Request the server to greet you
      operationId: getHelloWorld
      parameters:
        - $ref: "#/components/parameters/x-okapi-tenant"
        - name: salutation
          in: query
          schema:
            type: string
            default: "Welcome"
          example: "Greetings"
          description: The requested salutation
          required: false
      responses:
        "200":
          description: A hello-related message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/greeting"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/internalServerError"
    post:
      description: Parameter consumption example
      operationId: postHello
      parameters:
        - $ref: "#/components/parameters/x-okapi-tenant"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/arithmeticRequest"
      responses:
        "200":
          description: Basic maths
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/arithmetics"
        "400":
          description: Invalid parameter
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                invalidParameterError:
                  $ref: "#/components/examples/invalidParameterError"
                divideByZeroError:
                  value:
                    timestamp: 2021-11-18T13:38.51-50:00
                    status: 400
                    errors:
                      - code: hello.post.bad_arithmetic
                        message: Cannot divide by zero (parameter b = 0)
                  summary: Division by zero error
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/internalServerError"
  /calendar/periods/{servicePointId}/period:
    post:
      operationId: addNewPeriod
      description: Create a new period (calendar) for a service point
      parameters:
        - $ref: "#/components/parameters/x-okapi-tenant"
        - in: path
          name: servicePointId
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID for the relevant service point
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/period"
      responses:
        "201":
          description: The created period
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/period"
        "400":
          description: Invalid request (could not be understood)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/invalidRequest"
        "409":
          description: Request conflicts with existing data (duplicate ID, overlapping dates, etc)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/invalidData"
        "422":
          description: Invalid data (for example, start date after end date)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/invalidData"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              example:
                $ref: "#/components/examples/internalServerError"
components:
  schemas:
    period:
      $ref: schemas/period.yaml
    greeting:
      $ref: schemas/greeting.yaml
    arithmetics: # put here as example of inline schema
      type: object
      properties:
        product:
          description: a times b
          type: integer
        sum:
          description: a plus b
          type: integer
        quotient:
          description: a divided by b
          type: number
      required:
        - product
        - sum
        - quotient
      additionalProperties: false
      example:
        product: 15
        sum: 8
        quotient: 0.6
    arithmeticRequest:
      type: object
      properties:
        a:
          type: integer
        b:
          type: integer
      required:
        - a
        - b
      additionalProperties: false
      example:
        a: 3
        b: 5
    errorResponse:
      description: A set of error(s) from a request
      type: object
      properties:
        timestamp:
          description: The time that the error occurred
          type: string
          format: date-time
        status:
          description: The HTTP response code
          type: integer
        errors:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/error"
      additionalProperties: false
      required:
        - timestamp
        - status
        - errors
      example:
        $ref: "#/components/examples/internalServerError"
    error:
      $ref: schemas/error.yaml
  parameters:
    x-okapi-tenant:
      name: x-okapi-tenant
      in: header
      description: X-Okapi-Tenant Value
      required: true
      schema:
        type: string
  examples:
    internalServerError:
      value:
        timestamp: 2021-11-18T13:38.51-05:00
        status: 500
        errors:
          - error_code: internalServerError
            error_message: Internal Server Error
      summary: Any kind of internal error
    invalidRequest:
      value:
        timestamp: 2021-11-18T13:38.51-50:00
        status: 422
        errors:
          - code: invalidRequest
            message: The request could not be parsed
      summary: The request could not be parsed/understood.
    invalidParameterError:
      value:
        timestamp: 2021-11-18T13:38.51-05:00
        status: 422
        errors:
          - code: invalidParameter
            message: One of the parameters was of the incorrect type
      summary: A parameter was not of the correct type
    invalidData:
      value:
        timestamp: 2021-11-18T13:38.51-05:00
        status: 422
        errors:
          - code: noName
            message: The request included an empty name
      summary: The request was understood, however, a parameter was invalid
